---
title: "Functions"
author: "Courtney Hart"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LIBRARY
```{r}
library(roxygen2)
```

# DATA
airtemp
```{r}
airtemps = c(212, 30, 78, 32)
celsius1 <- (airtemps[1] - 32) * 5/9
celsius2 <- (airtemps[2] - 32) * 5/9
celsius3 <- (airtemps[3] - 32) * 5/9
celsius4 <- (airtemps[4] - 32) * 5/9

```

# FUNCTIONS

Fahr to celsius Function
```{r}
fahr2celsius <- function(fahr) {
  celsius <- (fahr - 32) * 5/9
  return(celsius)
}
```

use our function
```{r}
celsius_f <- fahr2celsius(airtemps[1])
celsius_f == celsius1

celsius <- fahr2celsius(airtemps)
celsius4 == celsius[4]
celsius
```

Celsius to Fahr function
```{r}
#' converts celsius to fehrenheit temperatures
#' A little needed but more detailed expanation goes here
#' @param celsius the temperatue in degrees celsius to be converted
#' @return the temperature in fahrenheit
celsius2fahr <- function(cel) {
  fahr <- (cel * 9/5) + 32
  return(fahr)
}

fahr <- celsius2fahr(celsius)
fahr
```
